archivist_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 20

archivist_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 20

  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  open_loop: false
  vel_mode: true
  #full_mode: true
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 100000.0, 100000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]

  # Velocity commands timeout [s]
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_link

  # Odom frame_id
  odom_frame_id: odom

  # Publish limited velocity
  publish_cmd: false

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and diameter. These ara both optional
  # diff_drive_controller will attempt to read either one or both from the 
  # URDF if not specified as a parameter
  wheel_separation: 0.35
  wheel_radius: 0.075

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0 

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.2   # m/s
      min_velocity           : -0.5 #-0.5  # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0 #1 #3.5   # m/s^2
      has_jerk_limits        : false #true
      max_jerk               : 5.0   # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.2 #1.7   # rad/s
      min_velocity           : -1.2 #-1.7
      has_acceleration_limits: true
      max_acceleration       : 2.0 #0.8 #2 #2.5 #1 #1.5   # rad/s^2
      has_jerk_limits        : false #true
      max_jerk               : 5.0

